sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t archita0104/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true archita0104/docker-react npm run test